name: keep-render-warm

on:
  schedule:
    - cron: "*/10 * * * *"   # Keep the 10-minute frequency
  workflow_dispatch: {}      # lets you run it manually from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    concurrency:
      group: keep-render-warm
      cancel-in-progress: false
    steps:
      - name: Keep Render warm without affecting Discord
        run: |
          curl -fsS https://spore-inviter.onrender.com/warm || true
